name: "Code Review"

on:
  push:
    branches: ["main"]
    paths:
      - sources/**
  pull_request:
    types: [opened, synchronize]
    paths:
      - sources/**
  workflow_dispatch: {}

jobs:
  code_review:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"

      - name: Install dependencies
        run: yarn

      - name: Run linter
        run: yarn lint

      - name: Run type checker
        run: yarn typecheck
